version: '2'
volumes:
  postgres_data: {}
services:
  app:
    image: lsjunior/desafio-otimo-app:1.0.0
    ports:
      - "18080:18080/tcp"
    depends_on:
      - db
  db:
    image: lsjunior/desafio-otimo-db:1.0.0
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432/tcp"
  ui:
    image: lsjunior/desafio-otimo-ui:1.0.0
    ports:
      - "18000:80/tcp"
    depends_on:
      - app
