version: '2'
volumes:
  postgres_data: {}
services:
  app:
    image: adoptopenjdk:8u262-b10-jdk-openj9-0.21.0
    volumes:
      - ./volumes/app/app.jar:/app.jar:ro
    ports:
      - "18080:18080/tcp"
    links:
      - postgres:db
    command:
      - java -jar -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom /app.jar
  nginx:
    image: nginx:1.19.1
    volumes:
      - ./volumes/nginx/usr/share/nginx/html://usr/share/nginx/html:ro
    ports:
      - "18000:80/tcp"
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: otimo
      POSTGRES_USER: otimo
      POSTGRES_DB: otimo
    volumes:
      - ./volumes/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432/tcp"
