version: '2'
volumes:
  postgres_data: {}
services:
  app:
    image: lsjunior/desafio-otimo-app:1.0.0
    ports:
      - "18080:18080/tcp"
    links:
      - postgres:db
  nginx:
    image: lsjunior/desafio-otimo-ui:1.0.0
    ports:
      - "18000:80/tcp"
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: otimo
      POSTGRES_USER: otimo
      POSTGRES_DB: otimo
    volumes:
      - ./volumes/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432/tcp"
